spring:
  datasource:
    url: jdbc:postgresql://172.26.155.26:5432/db04?currentSchema=citizenship
    username: dwh_admin
    password: qwerty$4
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

logging:
  level:
    ru.antonov.bdid2.mapper: debug
    org:
      springframework: debug
      apache.ibatis: info
      org.mybatis: info
    com:
      zaxxer:
      #        hikari: debug