spring:
  datasource:
    url: jdbc:postgresql://172.24.14.110:5432/db04?currentSchema=visa
    username: visa
    password: visa-visa
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1

logging:
  level:
    ru.antonov.bdid2.mapper: debug
    org:
#      springframework: debug
      apache.ibatis: info
      org.mybatis: info
    com:
      zaxxer:
        #        hikari: debug

